First implementation of a more flexible search for Qt translation files
bitwiseworks/dooble-os2 pull request #12
Opened 2022-05-06 06:16 UTC by josch1710

Dooble behave very Windows like, in that it assumes that data files are where the executable is.
I have extended the locale file search, such that it adheres more to Qt's and unix path conventions.
On Unix system, it will search for locale file in /usr(/local)/share/dooble/translations and /opt(/local)/share/dooble/translations.
On OS/2, it will search for locale file in /@unixroot(/local)/share/dooble/translations.
The old behaviour for searching was preserved.
This hack should make packaging easier.

2022-11-04 00:05 UTC, dmik requested changes
Thanks for your effort, but the patch is not clean: it changes whitespace (which is not allowed - the original file's convention should be followed) and adds pointless empty lines (which is not allowed either). Could you please fix those problems?

2022-11-04 00:08 UTC, dmik commented
Also we updated to a newer upstream version and there are some conflicts that need resolving. Please look at those too.

2022-11-05 23:22 UTC, closed without merging

2022-11-05 23:31 UTC, dmik commented
I fixed indentation and also made the proposed code more optimal. Also, I fixed another Double bug where it says in `Translations/README`:
> The Translations directory must reside in the directory which houses the Dooble
executable.
but actually looked for them in the **current** directory instead.

In my version I also disabled loading `qtbase_xx.qm` if `dooble_xx.qm` was picked up from system directories because in this case it is supposed that the system Qt installation provides them (it is not the case in case of OS/2 RPMs but I will not pack `qtbase_xx.qm` with Double RPM anyway — Qt RPMs need to be fixed for that, see https://github.com/bitwiseworks/qtbase-os2/issues/131).

But nevertheless, this translation lookup logic in Dooble is just badly designed and written in the first place. E.g. there are combinations of a locale and a translation file which lead to the application to successfully load the translation file at startup but complain that it cannot find it in settings (and forcing English if the user presses Apply there). These combinations include files like `dooble_de_DE.qm` and `de_DE` locale. The code in Settings will only look for `dooble_de.qm` and if It is missing, it will complain. But `QTranslator` handles this situation properly. The whole code just needs to be completely redesigned and rewritten. Not my task as I'm not the Dooble author/contributor.

2022-11-06 10:55 UTC, josch1710 commented
Hi Dimitry.

Sorry, to answer so late. I looked at the upstream, where all the search code was removed, and everything is searched via the environment variable. Did you reincluded the old search code?

2022-11-06 11:42 UTC, dmik commented
Yes, I took your directory list as it totally makes sense, please check my commit (you perhaps overlooked it above, it's https://github.com/bitwiseworks/dooble-os2/commit/ecaef19430fae410c64301081cca12ab716bd3e6).

2022-11-06 13:04 UTC, josch1710 commented
Looks good. I'm occupied at the moment, but I try to compile tomorrow or so.

2022-11-07 07:34 UTC, josch1710 commented
Compiles fine on my system and finds the translations files in @unixroot.

2022-11-07 13:49 UTC, dmik commented
Perfect, thanks for testing. I even released a new Dooble RPM a couple of days ago using this new code and it should also work fine.